[package]
name = "d10"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
indicatif = { version = "0.18.3", features = ["rayon"] }
itertools = "0.14.0"
rayon = "1.11.0"
winnow = "0.7.14"