name: Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - run: cargo llvm-cov nextest
      # - uses: actions/checkout@v4

      # - uses: dtolnay/rust-toolchain@stable
      #   with:
      #     components: llvm-tools-preview

      # - uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: ${{ matrix.rust-version }}
      #     override: true
      # - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
      # - uses: taiki-e/cache-cargo-install-action@nextest

      # - name: Collect coverage data
      #   run: cargo llvm-cov nextest

      # # - name: Install Rust
      # #   uses: dtolnay/rust-toolchain@stable

      # # - name: Cache cargo registry
      # #   uses: actions/cache@v4
      # #   with:
      # #     path: ~/.cargo/registry
      # #     key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      # #     restore-keys: |
      # #       ${{ runner.os }}-cargo-registry-

      # # - name: Cache cargo index
      # #   uses: actions/cache@v4
      # #   with:
      # #     path: ~/.cargo/git
      # #     key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
      # #     restore-keys: |
      # #       ${{ runner.os }}-cargo-git-

      # # - name: Cache cargo build
      # #   uses: actions/cache@v4
      # #   with:
      # #     path: target
      # #     key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      # #     restore-keys: |
      # #       ${{ runner.os }}-cargo-build-target-

      # # - name: Install cargo-nextest
      # #   uses: taiki-e/install-action@nextest

      # # - name: Run tests with nextest
      # #   run: cargo nextest run
